### ISSUE TITLE
Shifted characters whilst using  Macros.type(PSTR cause remaining characters to remain shifted.

### ISSUE THREAD

**Issue by nevd** [keyboardio/Kaleidoscope-Macros#27] opened 2018-08-14 20:58 UTC
When using Macros.type(PSTR any shifted character in the string seems to cause the remaining characters to be uppercased or their shifted eqivilant.

Tested on completely stock Model-01 firmware with anykey macro results in.

- Size: firmware/Model01-Firmware/Model01-Firmware-0.0.0-gv1.22-25-g29c8-dirty.elf
  - Program:   22350 bytes (78.0% Full)
  - Data:       1796 bytes (70.2% Full)

When ready, hold down PROG, and press ENTER. Keep holding PROG until flashing starts...

Connecting to programmer: .
Found programmer: Id = "CATERIN"; type = S
    Software Version = 1.0; No Hardware Version given.
Programmer supports auto addr increment.
Programmer supports buffered memory access with buffersize=128 bytes.

Programmer supports the following devices:
    Device code: 0x44

 KEYBOARDIO MODEL )! _ KALEIDOSCOPE LOCALLY BUILT

There is a lot of inconsistent behaviour after the macro plays, most often my Mac stops responding to the keyboard entirely for some period of time.

The behavior on Windows is identical for the macro but the post macro effect can vary.

**Comment by obra** [comment] 2018-08-14 21:04
Hi Neville,

Can you tell me what version of the Arduino-Boards repo you're working with?
ᐧ

**Comment by nevd** [comment] 2018-08-14 21:28
commit 0aeda943d1f63978c060e86f3d60418d6f89e57e (HEAD -> master, origin/master, origin/HEAD, 607903f)
Author: Jesse Vincent <jesse@keyboard.io>
Date:   Fri Aug 10 22:49:46 2018 -0700

**Comment by obra** [comment] 2018-08-14 21:35
If you back down to 7e128a4156e53f95112e634d6f15d78e93c2d173 does it get
better?
ᐧ

**Comment by nevd** [comment] 2018-08-14 21:45
git checkout 7e128a4156e53f95112e634d6f15d78e93c2d173
M       libraries/Kaleidoscope
M       libraries/Kaleidoscope-Focus
M       libraries/Kaleidoscope-HIDAdaptor-KeyboardioHID
M       libraries/Kaleidoscope-Hardware-EZ-ErgoDox
M       libraries/Kaleidoscope-Hardware-Model01
M       libraries/Kaleidoscope-LEDControl
M       libraries/Kaleidoscope-Macros
M       libraries/Kaleidoscope-MagicCombo
M       libraries/Kaleidoscope-MouseKeys
M       libraries/Kaleidoscope-NumPad
M       libraries/Kaleidoscope-Qukeys
M       libraries/KeyboardioHID
M       libraries/KeyboardioScanner
Note: checking out '7e128a4156e53f95112e634d6f15d78e93c2d173'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 7e128a4 Blindly pull all plugins up to current

I then reflashed from a stock Model01-Firmware and I still have the issue, my own sketch is super buggy at the moment as my oneshots are causing all manner of issues.

KEYBOARDIO MODEL )! _ KALEIDOSCOPE LOCALLY BUILTKEYBOARDIO MODEL )! _ 

Are you able to reproduce this?

**Comment by obra** [comment] 2018-08-14 22:28
I can reproduce it, but what's weird is that up to very recently, the
behavior was weirdly even less deterministic.
ᐧ

**Comment by gedankenexperimenter** [comment] 2018-08-15 20:05
I had a guess about what was causing this, and even went so far as to test a fix, which appeared to work – then I discovered that I actually can't reproduce the problem. Can you guys confirm that you see the bug with a fresh clone of the Arduino-Boards repo? I've had no end of trouble keeping all the submodule trees up to date and clean; they're an absolute nightmare to work with.

**Comment by obra** [comment] 2018-08-15 20:07
Yes, I can 100% confirm that I can reliably reproduce this.

I'd love to know what the fix you were considering is.

Separately, I'd love to know anything you can tell me about  a situation
where "make update-submodules" in Arduino-Boards did not do what you wanted.
ᐧ

**Comment by gedankenexperimenter** [comment] 2018-08-16 02:18
Curious. I reliably can't reproduce this with the latest Arduino-Boards. I wonder why. The fix (not fully considered) was to clear the requested modifiers byte after sending the report (in HIDAdaptor) — I was guessing that would fix the problem.

As for the submodule updating problem — it fails whenever there are changes to the submodules that haven't been checked in. And it's not always obvious that a submodule isn't what you want it to be, even after running `make maintainer-update-submodules` — I've given up on those makefile shortcuts entirely, because they so rarely do what I want, and so often seem like they run successfully, despite failing.

**Comment by obra** [comment] 2018-08-16 03:05
I believe the issue with macros -may- be platform-dependent. It's
reasonably ok on OS X, and totally nutso on Linux. But I'm not sure yet.
Having apparently solved the OneShot issue, I agree that they appear to be
different issues,
ᐧ

**Comment by nevd** [comment] 2018-08-16 06:37
May I ask how you have solved the OneShot issues, I have had to remove all my OneShot definitions from both Windows and OSX layers as they are doing some very odd things on both OSes.

**Comment by nevd** [comment] 2018-08-23 15:17
Is it possible to get a list of different revisions to try. I have had to turn off oneshots for anything other than the OSL(Func) and I have definitely got an issue where when I hit a key I am getting a large amount of repetition. It is not constant but still quite frequent.

It is most commonly occuring after using a shifted character, or a function character, so when I hit ? I get ?????????????? for example.

I have taken the key off with a puller and blown some air around them but I am pretty sure this is related to the update I did a few weeks ago. I have never had any issue like this until that update.

**Comment by nevd** [comment] 2018-08-23 16:43
Jesse, when I tested the revision you asked I never updated the submodules, I have done that now and I am testing the macro string issue and I am finding the issue has stopped occuring.

So it was git checked <version> followed by a make update-submodule

I will test at this version for a while, slowly reintroducing oneshots as well.

**Comment by obra** [comment] 2018-08-23 19:32
Sounds like a plan :)
ᐧ

**Comment by algernon** [comment] 2018-08-31 09:28
The version macro of the factory firmware appears to work fine for me, both under Linux and OSX.

Should we consider the issue resolved?

**Comment by nevd** [comment] 2018-08-31 13:48
Is Jesse not able to reproduce this with the latest firmware?

I am happy roll forward and test if you have commited changes which you think resolve the issue.

**Comment by gedankenexperimenter** [comment] 2018-08-31 14:28
When you wrote, "…I no longer have the issue", I misunderstood, and thought that you had been using old versions of the submodules with Kaleidoscope up to date, but I see now that you meant the opposite. Perhaps @obra had the same misunderstanding?

If you use a current copy of everything, can you reproduce the problem? It appears that neither @algernon nor I can reproduce it, so we're either missing something or there's some random element involved.

**Comment by nevd** [comment] 2018-08-31 14:38
When I was doing my testing with @obra I did exactly what you suggested. I ruled out my sketch and module modifications. (I had added a few submodules I wanted to use)

I am taking my M01 home tonight, I can test again this weekend if it helps?

**Comment by algernon** [comment] 2018-08-31 16:28
If you could test again with everything rolled forward, that would be great help, @nevd! Thanks in advance!

**Comment by nevd** [comment] 2018-09-02 12:52
Re-tested in the following combinations and this issue seems to have been resolved.
HEAD of both Arduino Boards and Model 01 Firmware 
HEAD of both Arduino Boards and my own sketch https://github.com/nevd/keyboardio

**Comment by algernon** [comment] 2018-09-02 13:48
That's awesome to hear, thank you for the patience, and for the testing!

I'm closing the issue accordingly.

**Closed by algernon** 2018-09-02 13:48 UTC
